-- CHRONUS MTG FANTASY — Supabase schema
-- Execute once in the target Supabase project's SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.campaigns(
 id uuid primary key default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 name text not null check (char_length(trim(name)) between 1 and 120),
 invite_code text not null unique,
 created_at timestamptz not null default now()
);

create table if not exists public.campaign_members(
 id uuid primary key default gen_random_uuid(),
 campaign_id uuid not null references public.campaigns(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 role text not null check(role in('mestre','jogador')),
 created_at timestamptz not null default now(),
 unique(campaign_id,user_id)
);

create table if not exists public.characters(
 id uuid primary key default gen_random_uuid(),
 campaign_id uuid not null references public.campaigns(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 character_name text not null default '',
 sheet_data jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(campaign_id,user_id)
);

create table if not exists public.dice_logs(
 id bigint generated by default as identity primary key,
 campaign_id uuid not null references public.campaigns(id) on delete cascade,
 user_id uuid references auth.users(id) on delete set null,
 character_name text not null default '',
 player_name text not null default '',
 action_title text not null default 'Teste',
 dice_pool jsonb not null default '[]'::jsonb,
 roll_result text not null default '',
 breakdown text not null default '',
 is_gm_roll boolean not null default false,
 is_secret boolean not null default false,
 created_at timestamptz not null default now()
);

create index if not exists campaign_members_campaign_idx on public.campaign_members(campaign_id);
create index if not exists campaign_members_user_idx on public.campaign_members(user_id);
create index if not exists characters_campaign_idx on public.characters(campaign_id);
create index if not exists characters_user_idx on public.characters(user_id);
create index if not exists dice_logs_campaign_idx on public.dice_logs(campaign_id);
create index if not exists dice_logs_created_idx on public.dice_logs(created_at desc);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end $$;

drop trigger if exists characters_touch on public.characters;
create trigger characters_touch before update on public.characters
for each row execute function public.touch_updated_at();

create or replace function public.is_campaign_owner(p uuid)
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.campaigns where id=p and owner_id=auth.uid())
$$;

create or replace function public.is_campaign_member(p uuid)
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.campaign_members where campaign_id=p and user_id=auth.uid())
$$;

create or replace function public.create_campaign(p_name text)
returns public.campaigns
language plpgsql security definer set search_path=public as $$
declare c public.campaigns; code text;
begin
 if auth.uid() is null then raise exception 'Não autenticado'; end if;
 loop
  code=upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
  exit when not exists(select 1 from public.campaigns where invite_code=code);
 end loop;
 insert into public.campaigns(owner_id,name,invite_code)
 values(auth.uid(),trim(p_name),code) returning * into c;
 insert into public.campaign_members(campaign_id,user_id,role)
 values(c.id,auth.uid(),'mestre');
 return c;
end $$;

create or replace function public.join_campaign(p_invite_code text)
returns public.campaign_members
language plpgsql security definer set search_path=public as $$
declare c public.campaigns; m public.campaign_members; n int;
begin
 if auth.uid() is null then raise exception 'Não autenticado'; end if;
 select * into c from public.campaigns
 where invite_code=upper(trim(p_invite_code)) for update;
 if not found then raise exception 'Código de convite inválido'; end if;
 if exists(select 1 from public.campaign_members where campaign_id=c.id and user_id=auth.uid()) then
  select * into m from public.campaign_members where campaign_id=c.id and user_id=auth.uid();
  return m;
 end if;
 select count(*) into n from public.campaign_members where campaign_id=c.id and role='jogador';
 if n>=10 then raise exception 'Esta campanha já possui 10 jogadores'; end if;
 insert into public.campaign_members(campaign_id,user_id,role)
 values(c.id,auth.uid(),'jogador') returning * into m;
 return m;
end $$;

grant execute on function public.create_campaign(text) to authenticated;
grant execute on function public.join_campaign(text) to authenticated;

grant select,insert,update,delete on public.campaigns to authenticated;
grant select,insert,update,delete on public.campaign_members to authenticated;
grant select,insert,update,delete on public.characters to authenticated;
grant select,insert on public.dice_logs to authenticated;
grant usage,select on sequence public.dice_logs_id_seq to authenticated;

alter table public.campaigns enable row level security;
alter table public.campaign_members enable row level security;
alter table public.characters enable row level security;
alter table public.dice_logs enable row level security;

drop policy if exists campaigns_select on public.campaigns;
create policy campaigns_select on public.campaigns for select to authenticated
using(owner_id=auth.uid() or public.is_campaign_member(id));

drop policy if exists campaigns_insert on public.campaigns;
create policy campaigns_insert on public.campaigns for insert to authenticated
with check(owner_id=auth.uid());

drop policy if exists campaigns_update on public.campaigns;
create policy campaigns_update on public.campaigns for update to authenticated
using(owner_id=auth.uid()) with check(owner_id=auth.uid());

drop policy if exists campaigns_delete on public.campaigns;
create policy campaigns_delete on public.campaigns for delete to authenticated
using(owner_id=auth.uid());

drop policy if exists members_select on public.campaign_members;
create policy members_select on public.campaign_members for select to authenticated
using(user_id=auth.uid() or public.is_campaign_owner(campaign_id));

drop policy if exists members_insert on public.campaign_members;
create policy members_insert on public.campaign_members for insert to authenticated
with check(user_id=auth.uid() or public.is_campaign_owner(campaign_id));

drop policy if exists members_delete on public.campaign_members;
create policy members_delete on public.campaign_members for delete to authenticated
using(public.is_campaign_owner(campaign_id) or user_id=auth.uid());

drop policy if exists chars_select on public.characters;
create policy chars_select on public.characters for select to authenticated
using(user_id=auth.uid() or public.is_campaign_owner(campaign_id));

drop policy if exists chars_insert on public.characters;
create policy chars_insert on public.characters for insert to authenticated
with check(user_id=auth.uid() and public.is_campaign_member(campaign_id));

drop policy if exists chars_update on public.characters;
create policy chars_update on public.characters for update to authenticated
using(user_id=auth.uid() or public.is_campaign_owner(campaign_id))
with check(user_id=auth.uid() or public.is_campaign_owner(campaign_id));

drop policy if exists chars_delete on public.characters;
create policy chars_delete on public.characters for delete to authenticated
using(user_id=auth.uid() or public.is_campaign_owner(campaign_id));

drop policy if exists dice_select on public.dice_logs;
create policy dice_select on public.dice_logs for select to authenticated
using(public.is_campaign_member(campaign_id));

drop policy if exists dice_insert on public.dice_logs;
create policy dice_insert on public.dice_logs for insert to authenticated
with check(user_id=auth.uid() and public.is_campaign_member(campaign_id));

insert into storage.buckets(id,name,public)
values('character-art','character-art',false)
on conflict(id) do update set public=false;

drop policy if exists art_insert on storage.objects;
create policy art_insert on storage.objects for insert to authenticated
with check(bucket_id='character-art' and split_part(name,'/',1)=auth.uid()::text);

drop policy if exists art_update on storage.objects;
create policy art_update on storage.objects for update to authenticated
using(bucket_id='character-art' and split_part(name,'/',1)=auth.uid()::text);

drop policy if exists art_delete on storage.objects;
create policy art_delete on storage.objects for delete to authenticated
using(bucket_id='character-art' and split_part(name,'/',1)=auth.uid()::text);

drop policy if exists art_select on storage.objects;
create policy art_select on storage.objects for select to authenticated
using(bucket_id='character-art' and split_part(name,'/',1)=auth.uid()::text);

do $$
begin
  alter publication supabase_realtime add table public.characters;
exception when duplicate_object then null;
end $$;
